version: 2.1

orbs:
  node: circleci/node@5.2.0
  docker: circleci/docker@1.4.0

jobs:
  deloy:
    executor: docker/docker
    steps:
       - add_ssh_keys:
          fingerprints:
            - "de:ea:3f:c2:a1:c3:9b:4d:04:f0:03:d1:ef:b4:e9:12"
       - run: ssh -p  5999  -o StrictHostKeyChecking=no -v test@125.212.250.1 './deloy_linh.sh'
workflows:
  commit:
    jobs:
      - deloy:
          filters:
            branches:
              only:
                - main
    
